version: '3'

services:
  server:
    build: .
    image: subterfuge_server
    depends_on:
      - db
    volumes:
      - ".:/var/www"
    ports:
      - 5000:5000
  
  db:
    image: "redis:rc-alpine"
    command: redis-server --requirepass TODO:changethis
    volumes:
      - "./redis/:/data"
    ports:
      - 6379:6379
      
  server_test:
    build:
      context: .
      target: test
    depends_on:
      - db
      - server

volumes:
  db: {  }